---
- name: First play
  hosts: nodes
  gather_facts: yes
  gather_subset: min
  tasks:
    - debug:
        msg: "connection successfully"

    - become: true
      shell: cat /etc/hosts

    - block:
        - name: Print msg
          debug:
            msg: "message"
        - ignore_errors: true 
          fail:
            msg: "Failed message"
      rescue: 
        - debug:
            msg: "An error occured"

      always:
        - debug:
            msg: "Always show this message"
