---
- hosts: nodes
  gather_facts: false
  become: true
  roles:
    - mongodb
  tags:
    - mongodb

- name: Apply role keepalived
  hosts: keepalived
  gather_facts: false
  become: true
  roles:
    - keepalived
  tags:
    - keepalived
