mongodb:
  install_path: /opt/install/mongodb

keepalived:
  install_path: /opt/install/keepalived
  routers:
    - name: mongodb
      virtual_ip: 192.168.100.100/24
      interface: enp0s8
      checks:
        - name: mongodb
          port: 27017
