---
- name: Create DNS resolv.conf from template
  when: dns_servers is defined
  become: true
  blockinfile:
    path: /etc/resolv.conf
    insertbefore: BOF
    block: |
      {%- for dns in dns_servers -%}
      nameserver {{ dns }}
      {% endfor %}
    state: "{{ dns_state | default('absent') }}"

  #template:
  #  src: resolv.conf.j2
  #  dest: /etc/resolv.conf 
